@baseUrl = http://localhost:5000
@apiVersion = /api/v1/

# @name getOutputs
GET {{baseUrl}}{{apiVersion}}mixer/out
Content-Type: application/json

###

# @name getOutput
GET {{baseUrl}}{{apiVersion}}mixer/out/{0.0.0.00000000}.{3ad6b2f2-752b-4eb5-8922-fb3ab41f4161}
Content-Type: application/json

###

# @name setOutputData
PUT {{baseUrl}}{{apiVersion}}mixer/out/{0.0.0.00000000}.{548c2cc6-14d5-4c82-9ce6-aa90dd4d60d8}
Content-Type: application/json

{
    "session": 37056,
    "volume": 100,
    "mute": false
}

###

# @name getInputs
GET {{baseUrl}}{{apiVersion}}mixer/in
Content-Type: application/json

###

# @name setInputData
PUT {{baseUrl}}{{apiVersion}}mixer/in/{0.0.1.00000000}.{835fc5b5-aab3-4503-8301-92d448abd99a}
Content-Type: application/json

{
    "mute": true
}

###